#!/bin/sh

set -e

PROJECT_FILES="README.md README_CN.md etc/init.d/shell-sing-box etc/sing-box/custom.env etc/sing-box/fake_ip_filter.list usr/libexec/shell-sing-box/common.sh usr/libexec/shell-sing-box/core-install.sh usr/libexec/shell-sing-box/dashboard.sh usr/libexec/shell-sing-box/firewall.sh usr/libexec/shell-sing-box/generate-system-config.sh usr/libexec/shell-sing-box/prepare.sh usr/libexec/shell-sing-box/srs-update.sh usr/libexec/shell-sing-box/task.sh usr/sbin/ssb"
SRC_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

copy_tree() {
    src=$1
    dst=$2
    [ -d "$src" ] || return 0
    mkdir -p "$dst"
    cp -R "$src"/. "$dst"/
}

need_root() {
    [ "$(id -u)" = "0" ] || {
        echo "Please run as root on ImmortalWrt/OpenWrt."
        exit 1
    }
}

install_packages() {
    command -v opkg >/dev/null 2>&1 || return 0

    missing=
    command -v nft >/dev/null 2>&1 || missing="$missing nftables"
    command -v ip >/dev/null 2>&1 || missing="$missing ip-full"
    command -v wget >/dev/null 2>&1 || command -v curl >/dev/null 2>&1 || missing="$missing wget-ssl"
    [ -c /dev/net/tun ] || missing="$missing kmod-tun"

    if [ -n "$missing" ]; then
        opkg update || true
        opkg install $missing || true
    fi
}

fetch_file() {
    remote=$1
    out=$2
    mkdir -p "$(dirname "$out")"
    if command -v curl >/dev/null 2>&1; then
        curl -kfsSL -o "$out" "$remote" || return 1
    elif command -v wget >/dev/null 2>&1; then
        wget --no-check-certificate -q -O "$out" "$remote" || return 1
    else
        echo "ERROR: missing curl/wget"
        exit 1
    fi
}

bootstrap_remote() {
    [ -n "$url" ] || return 0
    if [ -f "$SRC_DIR/usr/libexec/shell-sing-box/common.sh" ]; then
        return 0
    fi

    tmp=${TMPDIR:-/tmp}/shell-sing-box-install.$$
    rm -rf "$tmp"
    mkdir -p "$tmp"
    echo "Downloading shell-sing-box installer files from: $url"
    for file in $PROJECT_FILES; do
        printf "  fetching %s... " "$file"
        if fetch_file "$url/$file" "$tmp/$file"; then
            echo "done."
        else
            echo "FAILED!"
            echo "ERROR: Failed to download $file from $url"
            exit 1
        fi
    done
    SRC_DIR="$tmp"
}

main() {
    need_root
    bootstrap_remote
    install_packages
    copy_tree "$SRC_DIR/etc" /etc
    copy_tree "$SRC_DIR/usr" /usr
    mkdir -p /etc/sing-box/generated /etc/sing-box/ruleset /etc/sing-box/ui /etc/sing-box/bin /tmp/shell-sing-box
    chmod 755 /etc/init.d/shell-sing-box
    chmod 755 /usr/libexec/shell-sing-box/*.sh
    chmod 755 /usr/sbin/ssb
    /usr/libexec/shell-sing-box/core-install.sh

    if [ ! -f /etc/sing-box/generated/config.json ]; then
        cat > /etc/sing-box/generated/README <<'EOF'
Put the sing-box config generated by your subscription generator here:

  /etc/sing-box/generated/config.json

The service will copy it to /tmp/shell-sing-box/config and add transparent
proxy, DNS, SRS cache, and Zashboard API fragments at startup.
EOF
    fi

    /etc/init.d/shell-sing-box enable || true
    echo "Installed shell-sing-box."
    echo "Next: put your generated config at /etc/sing-box/generated/config.json"
    echo "Then run: /etc/init.d/shell-sing-box start"
}

main "$@"
